apiVersion: v1
kind: Service
metadata:
 name: currency-exchange-rate-eks-sevice
spec:
 type: ClusterIP # Internal communication only. Not exposed to outside world
 selector:
   app: currency-exchange-rate-deployment-pod #defined in the deployment
 ports:
 - port: 8080 #where container is actually running
   targetPort: 8080 #port of this service. Cluster members talk via this port
